import numpy as np
import matplotlib.pylab as plt
datos=np.genfromtxt("datos_omega.dat", skip_header=1)
datoslp1=np.genfromtxt("datoslp1.dat")
datoslp2=np.genfromtxt("datoslp2.dat")
datoslp3=np.genfromtxt("datoslp3.dat")
datoslp4=np.genfromtxt("datoslp4.dat")
daticos=np.genfromtxt("datoslp.dat")
plt.figure(figsize=[10,10])
plt.scatter(datos[:,3],datos[:,0], c='pink', label="U1")
plt.scatter(datos[:,3],datos[:,1], c='cyan', label="U2")
plt.scatter(datos[:,3],datos[:,2], c='orange', label="U3")
plt.title("Maximas amplitudes para diferentes omegas")
plt.legend()
plt.xlabel("omega")
plt.ylabel("posicion(m)")
plt.savefig("plot_omegas.pdf")
plt.figure(figsize=[10,10])
plt.plot(daticos[:,3],daticos[:,0], c='pink', label="U1")
plt.plot(daticos[:,3],daticos[:,1], c='cyan', label="U2")
plt.plot(daticos[:,3],daticos[:,2], c='orange', label="U3")
plt.legend()
plt.title("Desplazamiento para omega=1*raiz(k/m)")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("plot_omegafijo.pdf")
x=datos[:,0]
y=datos[:,1]
z=datos[:,2]
c=datos[:,3]
pos_maxima=np.argmax(x)
omega1=(c[pos_maxima])
pos_minima=np.argmin(x)
omega2=(c[pos_minima])
pos_maxima1=np.argmax(y)
omega3=(c[pos_maxima1])
pos_minima1=np.argmin(z)
omega4=(c[pos_minima1])

plt.figure(figsize=[10,10])
plt.plot(datoslp1[:,3],datoslp1[:,0], c='pink', label="U1")
plt.plot(datoslp1[:,3],datoslp1[:,1], c='cyan', label="U2")
plt.plot(datoslp1[:,3],datoslp1[:,2], c='orange', label="U3")
plt.legend()
plt.title("Desplazamiento para el mayor omega de U1")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("plot_omega1.pdf")
plt.figure(figsize=[10,10])
plt.plot(datoslp2[:,3],datoslp2[:,0], c='pink', label="U1")
plt.plot(datoslp2[:,3],datoslp2[:,1], c='cyan', label="U2")
plt.plot(datoslp2[:,3],datoslp2[:,2], c='orange', label="U3")
plt.legend()
plt.title("Desplazamiento para el menor omega de U1")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("plot_omega2.pdf")
plt.figure(figsize=[10,10])
plt.plot(datoslp4[:,3],datoslp4[:,0], c='pink', label="U1")
plt.plot(datoslp4[:,3],datoslp4[:,1], c='cyan', label="U2")
plt.plot(datoslp4[:,3],datoslp4[:,2], c='orange', label="U3")
plt.legend()
plt.title("Desplazamiento para el menor omega de U3")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("plot_omega4.pdf")
plt.figure(figsize=[10,10])
plt.plot(datoslp3[:,3],datoslp3[:,0], c='pink', label="U1")
plt.plot(datoslp3[:,3],datoslp3[:,1], c='cyan', label="U2")
plt.plot(datoslp3[:,3],datoslp3[:,2], c='orange', label="U3")
plt.legend()
plt.title("Desplazamiento para el mayor omega de U2")
plt.xlabel("tiempo(s)")
plt.ylabel("posicion(m)")
plt.savefig("plot_omega3.pdf")